### PR TITLE
Update EnhancedDataset closing method

### PR DESCRIPTION
**Pull request by RSully**
This updates how our Dataset subclasses close and uses the new `isopen()` method introduced in v1.2.0 of netCDF4.

### CODE REVIEW

**Comment by kwilcox** [comment]
I think the only bug was calling `self.close()` instead of super().close(), which you fixed. Does PyCharm still crash with just that fix?

**Comment by RSully** [comment]
No crash, but the tests fail.

**Comment by kwilcox** [comment]
What's the stack trace look like?

**Comment by RSully** [comment]
```
______________________________ TestTimeSeries.test_extracting_dataframe_all_masked_heights _______________________________

self = <pyaxiom.tests.test_timeseries.TestTimeSeries testMethod=test_extracting_dataframe_all_masked_heights>

    def test_extracting_dataframe_all_masked_heights(self):
        filename = 'test_extracting_dataframe_all_masked_heights.nc'
        times = [0, 1000, 2000, 3000, 4000, 5000]
        verticals = [-9999.9]
        ts = TimeSeries(output_directory=self.output_directory,
                        latitude=self.latitude,
                        longitude=self.longitude,
                        station_name=self.station_name,
                        global_attributes=self.global_attributes,
                        output_filename=filename,
                        times=times,
                        verticals=verticals,
                        vertical_fill=-9999.9)
    
        values = np.repeat([20, 21, 22, 23, 24, 25], len(verticals))
        attrs = dict(standard_name='sea_water_temperature')
>       ts.add_variable('temperature', values=values, attributes=attrs)

pyaxiom/tests/test_timeseries.py:468: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyaxiom/netcdf/sensors/timeseries.py:264: in add_variable
    elif self.z.size == 1:
netCDF4/_netCDF4.pyx:3389: in netCDF4._netCDF4.Variable.size.__get__ (netCDF4/_netCDF4.c:33021)
    ???
netCDF4/_netCDF4.pyx:3378: in netCDF4._netCDF4.Variable.shape.__get__ (netCDF4/_netCDF4.c:32765)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: NetCDF: Not a valid ID

netCDF4/_netCDF4.pyx:3323: RuntimeError
```

See comment [here](https://github.com/axiom-data-science/pyaxiom/pull/7#commitcomment-17719403)

**Comment by kwilcox** [comment]
Nice catch! instead of using `self.z` in `add_variable`, lets create a locally scoped variable and use that.

```python
with EnhancedDataset(self.out_file, 'r') as nc::
    some_local_z_var = nc.variables[self.vertical_axis_name]
```

**Pull request merged**
